### ISSUE TITLE
Status indicators: Bar gets "stuck" when resizing out of bounds.

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#49] opened 2017-07-26 20:53 UTC
By resizing the status indicator bar to a point that exceeds the client, it'll get stuck and you're unable to resize it back down again. Is applicable to both "directions" of the bar.

https://gfycat.com/ChillyGraveElectriceel

Also causes a massive performance impact. 
![image](https://user-images.githubusercontent.com/30437792/28643419-0d4b3a84-7256-11e7-9e5b-c5619ab0d099.png) 
![image](https://user-images.githubusercontent.com/30437792/28643429-19442e04-7256-11e7-98fe-78fb1d721f2d.png)

OSBuddy v3.0.12
Windows 10

**Comment by rsbmatt** [comment] 2017-08-08 16:34
Does this still happen?

**Comment by rsbfox** [comment] 2017-08-09 16:18
If this was supposed to be fixed in v3.0.16.

Someone got it stuck and they needed to delete orion.ini
Was caused by gwd adding 23 skill icons from lowered stats.

**Closed as completed** 2017-08-19 02:48 UTC
Labels: res-fixed
