### ISSUE TITLE
Cannonballs: Efficient cannon position at Suqahs

### ISSUE THREAD

**Issue by rsnjames** [rsbmatt/OSBuddy#28] opened 2017-07-25 18:12 UTC
The efficient cannon position for suqahs should be moved 1 square west. 

Current tile: (2115, 3943)
Preposed tile: (2114, 3943)

OSB version 3.0.11

**Comment by rsbfox** [comment] 2017-07-25 18:40
Need a reference on what spot is most efficient. Ask Randalicious to confirm.

**Comment by rsnjames** [comment] 2017-07-25 18:52
SKDudeman posted about it, but I'll ask Randalicious too

**Comment by rsbfox** [comment] 2017-07-25 18:56
![image](https://user-images.githubusercontent.com/30416150/28588729-7a4bcbf2-7149-11e7-8364-029e43cfee56.png)

**Comment by SKDudeMan** [comment] 2017-07-26 07:11
Currently, the spot says we need to place the cannon on the dirt pile, but the efficient spot is to place it 1 west of it (the correct spot should be where I'm standing). 
<img width="460" alt="suqahs wrong cannon spot" src="https://user-images.githubusercontent.com/30426580/28608795-91a9c918-7214-11e7-837f-8cd9ef1bcac1.png">

This video explains why it should be moved 1sq west of where it currently is (I've linked it with the correct time).
https://youtu.be/jGZi9zZejIM?t=1m47s

**Comment by rsbfox** [comment] 2017-07-26 13:28
![image](https://user-images.githubusercontent.com/30416150/28623694-c7877dd0-71e4-11e7-8dd9-280638883f0f.png)
Leaving issue open till xp rate testing is done.
Preposed tile
![image](https://user-images.githubusercontent.com/30416150/28627421-c6c4cfc8-71ef-11e7-9da3-358cc65dd80c.png)

**Comment by Joord** [comment] 2017-07-26 16:12
Could you please provide the tile location as is provided in #45.

Thank you :)

**Comment by rsbfox** [comment] 2017-07-26 16:34
Sure but we have not decided which is better yet.

**Comment by rsbfox** [comment] 2017-07-26 16:39
Randalicious is testing other tile now.

**Comment by rsbfox** [comment] 2017-07-26 16:46
Current tile
![image](https://user-images.githubusercontent.com/30416150/28632996-4ac2b334-7200-11e7-9010-bda32eab9ecc.png)

Closing issue as by design.

**Closed as completed by rsbfox** 2017-07-26 16:46 UTC
Labels: res-by design
